# Generated by Django 2.2.1 on 2019-05-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=50)),
                ('jianjie', models.CharField(max_length=200)),
                ('fo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foods.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('littletitle', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=200, null=True)),
                ('littlebody', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('fo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foods.Title')),
            ],
        ),
    ]
