# Generated by Django 2.2.1 on 2019-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0002_body_people_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('desc', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': '人物', 'verbose_name_plural': '人物'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '标题', 'verbose_name_plural': '标题'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
