# Generated by Django 2.2.1 on 2019-05-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0003_auto_20190528_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=50)),
                ('detal', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '建议',
                'verbose_name_plural': '建议',
            },
        ),
    ]
