# Generated by Django 2.2.1 on 2019-05-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='')),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '厨师',
                'verbose_name_plural': '厨师',
            },
        ),
    ]
