# Generated by Django 2.2.1 on 2019-05-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0005_cook_shop_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(default=' ', max_length=10)),
                ('body', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'verbose_name': '样式',
                'verbose_name_plural': '样式',
            },
        ),
    ]
