# Generated by Django 2.2.1 on 2019-05-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0007_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '荣誉',
                'verbose_name_plural': '荣誉',
            },
        ),
    ]
