# Generated by Django 2.2.1 on 2019-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0008_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
