# Generated by Django 2.2.1 on 2019-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0012_auto_20190530_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='img',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
