# Generated by Django 2.2.1 on 2019-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0013_log_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='img2',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
