# Generated by Django 2.2 on 2019-05-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20190517_1657'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='goods',
            managers=[
            ],
        ),
    ]
