# Generated by Django 2.2 on 2019-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_messageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
    ]
