# Generated by Django 2.2 on 2019-05-23 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discuss',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.RenameField(
            model_name='discuss',
            old_name='comments',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='comment',
        ),
        migrations.AddField(
            model_name='discuss',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discuss',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discuss',
            name='urls',
            field=models.URLField(max_length=50),
        ),
    ]
